---
title: "app ideas"
author: "Zachary Hamilton"
date: "06/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(extrafont)


theme_set(theme_minimal() +
          theme(text = element_text(family = "Verdana"),
                panel.grid.major.x = element_blank(),
                panel.grid.minor.x = element_blank()))


climate_daily <- read_csv("data/climate_daily.csv")
climate_hourly <- read_csv("data/climate_hourly.csv")
climate_monthly <- read_csv("data/climate_monthly.csv")
climate_yearly <- read_csv("data/climate_yearly.csv")
stations <- read_csv("data/station_info.csv")

```

```{r}
#Temperature totals


#temp
climate_daily %>%
  filter(year(date) == 2015, city %in% c("Vancouver", "Toronto")) %>%
  mutate(city = fct_reorder(city, temp_mean, mean)) %>%
  ggplot(aes(date, temp_mean, col = city)) +
  geom_line() +
  geom_point() +
  geom_ribbon(aes(ymin = temp_min, ymax = temp_max, fill = city), alpha = 0.2) +
  scale_color_brewer(name = "City", type = "div", palette = "Accent") +
  scale_fill_brewer(name = "City", type = "div", palette = "Accent") +
  labs(title = "Mean daily temperature",
       subtitle = "Ribbons indicate min/max observations",
       x = "",
       y = "Temperature (C)",
       caption = "Data obtained from ECCC")

#fix date 
climate_monthly %>%
  mutate(date = ymd(paste(year, month, "15", sep = "-"))) %>%
  filter(year(date) %in% 2010:2015, city %in% c("Vancouver", "Toronto")) %>%
  mutate(city = fct_reorder(city, temp_mean, mean)) %>%
  ggplot(aes(date, temp_mean, col = city)) +
  geom_line() +
  geom_point() +
  geom_ribbon(aes(ymin = temp_min, ymax = temp_max, fill = city), alpha = 0.2) +
  scale_color_brewer(name = "City", type = "div", palette = "Accent") +
  scale_fill_brewer(name = "City", type = "div", palette = "Accent") +
  labs(title = "Mean daily temperature",
       subtitle = "Ribbons indicate min/max observations",
       x = "",
       y = "Temperature (C)",
       caption = "Data obtained from ECCC")

climate_yearly %>%
  mutate(date = ymd(paste(year, "06", "15", sep = "-"))) %>%
  filter(year(date) %in% 2010:2015, city %in% c("Vancouver", "Toronto")) %>%
  mutate(city = fct_reorder(city, temp_mean, mean)) %>%
  ggplot(aes(date, temp_mean, col = city)) +
  geom_line() +
  geom_point() +
  geom_ribbon(aes(ymin = temp_min, ymax = temp_max, fill = city), alpha = 0.2) +
  scale_color_brewer(name = "City", type = "div", palette = "Accent") +
  scale_fill_brewer(name = "City", type = "div", palette = "Accent") +
  labs(title = "Mean daily temperature",
       subtitle = "Ribbons indicate min/max observations",
       x = "",
       y = "Temperature (C)",
       caption = "Data obtained from ECCC")


```


```{r}

##precip static

climate_daily %>%
  filter(year(date) == 2018, city %in% c("Vancouver", "Toronto", "Montreal", "Victoria", "Ottawa"),
         !is.na(total_precip)) %>%
  mutate(city = fct_reorder(city, total_precip, sum, .desc = TRUE)) %>%
  group_by(city) %>%
  mutate(cum_total_precip = cumsum(total_precip)) %>% 
  ggplot(aes(date, cum_total_precip, col = city)) +
  geom_line(size = .9) +
  theme(text = element_text(size = 14)) +
  scale_color_brewer(name = "City", palette = "Blues") +
  labs(title = "Cumulative Precipitation",
       x = "",
       y = "Total Precipitation (mm)",
       caption = "Data obtained from ECCC")


climate_monthly %>%
  mutate(date = ymd(paste(year, month, "15", sep = "-"))) %>%
  filter(year == 2017,
         !is.na(total_precip_sum)) %>%
  mutate(city = fct_reorder(city, total_precip_sum, sum, .desc = TRUE)) %>%
  group_by(city, year) %>%
  mutate(cum_total_precip = cumsum(total_precip_sum)) %>% 
  ggplot(aes(date, cum_total_precip, col = city)) +
  geom_line(size = .9) +
  geom_point() +
  theme(text = element_text(size = 14)) +
  scale_color_brewer(name = "City", palette = "Blues") +
  labs(title = "Cumulative Precipitation 2018",
       x = "",
       y = "Total Precipitation (mm)",
       caption = "Data obtained from ECCC")


climate_yearly %>%
  mutate(date = ymd(paste(year, "06", "15", sep = "-"))) %>%
  filter(year %in% 2014:2015,
         !is.na(total_precip_sum)) %>% 
  mutate(city = fct_reorder(city, total_precip_sum, sum, .desc = TRUE, na.rm = TRUE)) %>%
  group_by(city) %>%
  mutate(cum_total_precip = cumsum(total_precip_sum)) %>%
  ggplot(aes(date, cum_total_precip, col = city)) +
  geom_line(size = .9) +
  geom_point() +
  theme(text = element_text(size = 14)) +
  scale_color_brewer(name = "City", palette = "Blues") +
  labs(title = "Cumulative Precipitation",
       x = "",
       y = "Total Precipitation (mm)",
       caption = "Data obtained from ECCC")
```


```{r}
#precip animation
library(gganimate)

p <- climate_daily %>%
  filter(year(date) == 2018, city %in% c("Vancouver", "Toronto", "Montreal", "Victoria", "Ottawa"),
         !is.na(total_precip)) %>%
  mutate(city = fct_reorder(city, total_precip, sum, .desc = TRUE)) %>%
  group_by(city) %>%
  mutate(cum_total_precip = cumsum(total_precip)) %>% 
  ggplot(aes(date, cum_total_precip, col = city)) +
  geom_line(size = .9) +
  geom_image(aes(image = "img/raindrop.png"), size = 0.02 ) +
  theme(text = element_text(size = 14)) +
  scale_color_discrete(name = "City") +
  labs(title = "Cumulative Precipitation 2018",
       x = "",
       y = "Total Precipitation (mm)",
       caption = "Data obtained from ECCC") +
  transition_reveal(id = city, along = date) 

animate(p, nframes = 50)

anim_save("plots/precip_anim_loop.gif")
```


```{r}
        switch("monthly",
                "daily" = climate_daily,
                "monthly" = climate_monthly,
                "yearly" = climate_yearly) %>%
      filter(year )
```


```{r}
climate_daily %>%
  group_by(city) %>%
  mutate(cum_total_precip = cumsum(total_precip)) %>% summary()

climate_yearly %>%
  group_by(city)
```


```{r}
#### ----------------------------------------------------------------------

climate_hourly_raw <- read_csv("data/climate_hourly_raw.csv")
climate_daily_raw <- read_csv("data/climate_daily_raw.csv")



climate_daily_van_raw <- weather_dl(c(833, 889, 51442), start = "1900-01-01", interval = "day")

theme_set(theme_minimal() +
            theme(text = element_text(family = "Verdana"),
                  panel.grid.major.x = element_blank(),
                  panel.grid.minor.x = element_blank()))

climate_daily_van <- climate_daily_van_raw %>%
  mutate(region = case_when(str_detect(station_name, "WHARVES") ~ "North Van (Wharf)",
                            TRUE ~ "YVR")) %>%
  select(region, date, year, month, day, total_precip) %>%
  filter(!is.na(total_precip), year >= 1962)


data <- climate_daily_van %>%
  group_by(region, year) %>%
  mutate(cum_total_precip = cumsum(total_precip)) %>% 
  summarize(`total_precip (mm)` = max(cum_total_precip)) %>%
  arrange(desc(`total_precip (mm)`)) %>%
  ungroup() %>%
  mutate(rank = row_number()) %>%
  filter(rank <= 50)

  ggplot(data, aes(rank, `total_precip (mm)`, fill = region)) +
  geom_col(position = "dodge") +
  geom_label_repel(data = data %>% group_by(region) %>%
                      filter(`total_precip (mm)` == max(`total_precip (mm)`)),
             aes(label = paste(year, ", ", `total_precip (mm)`, "mm", sep = ""))) +
  scale_fill_manual(name = "Station", values = c("#195fd1", '#84d119')) +
  labs(title = "Top 50 Highest precipitation years since 1962 (North Van/YVR)",
       subtitle = "top 41 all belong to North Van",
       x = "Rank",
       y = "Total Yearly Precipitation",
       caption = "data obtained from ECCC")

climate_daily_van %>%
  filter(year %in% c(2015, 2016, 2017, 2018)) %>%
  group_by(region, year) %>%
  mutate(cum_total_precip = cumsum(total_precip)) %>% 
  ggplot(aes(date, cum_total_precip, col = region)) +
  geom_line(size = 1.2) +
  scale_color_manual(name = "Station", values = c("#195fd1", '#84d119')) +
  theme(axis.text.x = element_blank()) +
  facet_wrap(~year, scales = "free_x") +
  labs(title = "Precipitation disparity between North Van and YVR",
       x = "",
       y = "Cumulative total precip (mm)",
       caption = "data obtained from ECCC")

```

